name: uuid_to_hsl
description: Flutter plugin to get a color from a UUID in HSL color space.
repository: https://github.com/merkator95/uuid_to_hsl
version: 1.0.0
homepage:

environment:
  sdk: '>=3.10.0 <4.0.0'
  flutter: ">=3.38.10"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^9.0.0
